DROP INDEX IDX_PRJ_PRO_FLOW_ID01;

CREATE INDEX IDX_PRJ_PRO_FLOW_ID01
ON REQ4100 (PRJ_ID, PROCESS_ID, FLOW_ID, REQ_ID)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE USERS
COMPUTE STATISTICS
ONLINE;