DROP INDEX IDX_PRJ_REQ_DTM;

CREATE INDEX IDX_PRJ_REQ_DTM
ON REQ4900 (PRJ_ID, REQ_ID, REG_DTM)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE USERS
COMPUTE STATISTICS
ONLINE;