DROP INDEX IDX_SEARCH_DEL_CHK;

CREATE INDEX IDX_SEARCH_DEL_CHK
ON ARM1000 (DEL_CHECK)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_OSLAGL_DAT01
COMPUTE STATISTICS
ONLINE;