DROP INDEX IDX_WHERE_USR_ID;

CREATE INDEX IDX_WHERE_USR_ID
ON ARM1000 (USR_ID)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_OSLAGL_DAT01
COMPUTE STATISTICS
ONLINE;