

/* ADM1000 테이블 생성 SQL */
CREATE TABLE ADM1000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          MENU_ID VARCHAR(12) COLLATE utf8_bin NOT NULL ,
          UPPER_MENU_ID VARCHAR(14) COLLATE utf8_bin NULL ,
          MENU_NM VARCHAR(200) COLLATE utf8_bin NOT NULL ,
          MENU_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          MENU_DESC VARCHAR(500) COLLATE utf8_bin NULL ,
          MENU_URL VARCHAR(500) COLLATE utf8_bin NULL ,
          MENU_PATH VARCHAR(500) COLLATE utf8_bin NULL ,
          MENU_IMG_URL VARCHAR(500) COLLATE utf8_bin NULL ,
          LVL INT NULL ,
          ORD INT NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          PRJ_TYPE VARCHAR(16) COLLATE utf8_bin NULL ,
          MODULE_TYPE VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM1000 PRIMARY KEY ( LIC_GRP_ID, MENU_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM1000','OSLITSDB') ON CLASS db_authorizations;


/* ADM1100 테이블 생성 SQL */
CREATE TABLE ADM1100 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          AUTH_GRP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          AUTH_GRP_NM VARCHAR(50) COLLATE utf8_bin NOT NULL ,
          AUTH_GRP_DESC VARCHAR(500) COLLATE utf8_bin NULL ,
          CREATE_DT VARCHAR(8) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          ORD INT NULL ,
          USR_TYP CHAR(2) COLLATE utf8_bin NULL ,
          ACCEPT_USE_CD CHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM1100 PRIMARY KEY ( LIC_GRP_ID, PRJ_ID, AUTH_GRP_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM1100','OSLITSDB') ON CLASS db_authorizations;


/* ADM1200 테이블 생성 SQL */
CREATE TABLE ADM1200 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          AUTH_GRP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          MENU_ID VARCHAR(12) COLLATE utf8_bin NOT NULL ,
          MAIN_YN CHAR(1) COLLATE utf8_bin NULL ,
          ACCESS_YN CHAR(1) COLLATE utf8_bin NULL ,
          SELECT_YN CHAR(1) COLLATE utf8_bin NULL ,
          REG_YN CHAR(1) COLLATE utf8_bin NULL ,
          MODIFY_YN CHAR(1) COLLATE utf8_bin NULL ,
          DEL_YN CHAR(1) COLLATE utf8_bin NULL ,
          EXCEL_YN CHAR(1) COLLATE utf8_bin NULL ,
          PRINT_YN CHAR(1) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM1200 PRIMARY KEY ( LIC_GRP_ID, PRJ_ID, AUTH_GRP_ID, MENU_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM1200','OSLITSDB') ON CLASS db_authorizations;


/* ADM1300 테이블 생성 SQL */
CREATE TABLE ADM1300 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          AUTH_GRP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          USR_ID VARCHAR(20) COLLATE utf8_bin NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM1300 PRIMARY KEY ( PRJ_ID, AUTH_GRP_ID, USR_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM1300','OSLITSDB') ON CLASS db_authorizations;



/* ADM2000 테이블 생성 SQL */
CREATE TABLE ADM2000 (
          USR_ID VARCHAR(20) COLLATE utf8_bin NOT NULL ,
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          USR_PW VARCHAR(200) COLLATE utf8_bin NOT NULL ,
          USR_NM VARCHAR(200) COLLATE utf8_bin NOT NULL ,
          EMAIL VARCHAR(50) COLLATE utf8_bin NULL ,
          TELNO VARCHAR(20) COLLATE utf8_bin NULL ,
          DEPT_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          ETC VARCHAR(4000) COLLATE utf8_bin NULL ,
          WK_ST_TM CHAR(4) COLLATE utf8_bin NULL ,
          WK_ED_TM CHAR(4) COLLATE utf8_bin NULL ,
          BK_ST_TM CHAR(4) COLLATE utf8_bin NULL ,
          BK_ED_TM CHAR(4) COLLATE utf8_bin NULL ,
          PW_FAIL_CNT INT NULL ,
          BLOCK VARCHAR(2) COLLATE utf8_bin NULL ,
          ADM_YN CHAR(1) COLLATE utf8_bin NULL ,
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          USR_IMG_ID CHAR(20) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          USR_POSITION_CD  VARCHAR(2) COLLATE utf8_bin NULL ,
          USR_DUTY_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REQ_MAIN_COLOR VARCHAR(10) COLLATE utf8_bin NULL ,
          REQ_FONT_COLOR VARCHAR(10) COLLATE utf8_bin NULL ,
          INI_YN CHAR(1) COLLATE utf8_bin NULL ,
          INI_DTM DATETIME NULL ,
          REC_LOGIN_DTM DATETIME NULL ,
          DSH_DISPLAY_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM2000 PRIMARY KEY ( USR_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM2000','OSLITSDB') ON CLASS db_authorizations;


/* ADM2100 테이블 생성 SQL */
CREATE TABLE ADM2100 (
          USR_ID VARCHAR(20) COLLATE utf8_bin NOT NULL ,
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          SEQ INT NOT NULL ,
          BLK_LOG VARCHAR(1000) COLLATE utf8_bin NULL ,
          REC_LOGIN_DTM DATETIME NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM2100 PRIMARY KEY ( USR_ID, LIC_GRP_ID, SEQ )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM2100','OSLITSDB') ON CLASS db_authorizations;


/* ADM3000 테이블 생성 SQL */
CREATE TABLE ADM3000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          LIC_NO VARCHAR(20) COLLATE utf8_bin NOT NULL ,
          LIC_NM VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          LIC_START_DT CHAR(8) COLLATE utf8_bin NOT NULL ,
          LIC_END_DT CHAR(8) COLLATE utf8_bin NOT NULL ,
          LIC_GB_CD VARCHAR(2) COLLATE utf8_bin NOT NULL ,
          PERMIT_USR_CNT INT NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM3000 PRIMARY KEY ( LIC_GRP_ID, LIC_NO )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM3000','OSLITSDB') ON CLASS db_authorizations;


/* ADM3100 테이블 생성 SQL */
CREATE TABLE ADM3100 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM3100 PRIMARY KEY ( LIC_GRP_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM3100','OSLITSDB') ON CLASS db_authorizations;

 
/* ADM4000 테이블 생성 SQL */
CREATE TABLE ADM4000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          MST_CD VARCHAR(8) COLLATE utf8_bin NOT NULL ,
          UPPER_MST_CD VARCHAR(8) COLLATE utf8_bin NULL ,
          MST_CD_NM VARCHAR(50) COLLATE utf8_bin NOT NULL ,
          MST_CD_ENG_NM VARCHAR(50) COLLATE utf8_bin NULL ,
          MST_CD_DESC VARCHAR(200) COLLATE utf8_bin NULL ,
          ABORT_DT CHAR(8) COLLATE utf8_bin NULL ,
          LVL INT NULL ,
          ORD INT NULL ,
          USE_YN CHAR(1) COLLATE utf8_bin NULL ,
          STM_USE_YN CHAR(1) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM4000 PRIMARY KEY ( LIC_GRP_ID, MST_CD )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM4000','OSLITSDB') ON CLASS db_authorizations;

 
/* ADM4100 테이블 생성 SQL */
CREATE TABLE ADM4100 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          MST_CD VARCHAR(8) COLLATE utf8_bin NOT NULL ,
          SUB_CD VARCHAR(2) COLLATE utf8_bin NOT NULL ,
          SUB_CD_NM VARCHAR(50) COLLATE utf8_bin NOT NULL ,
          ORD INT NULL ,
          USE_YN CHAR(1) COLLATE utf8_bin NULL ,
          SUB_CD_REF1 VARCHAR(50) COLLATE utf8_bin NULL ,
          SUB_CD_REF2 VARCHAR(50) COLLATE utf8_bin NULL ,
          SUB_CD_REF3 VARCHAR(50) COLLATE utf8_bin NULL ,
          SUB_CD_REF4 VARCHAR(50) COLLATE utf8_bin NULL ,
          SUB_CD_REF5 VARCHAR(50) COLLATE utf8_bin NULL ,
          SUB_CD_DESC VARCHAR(200) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM4100 PRIMARY KEY ( LIC_GRP_ID, MST_CD, SUB_CD )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM4100','OSLITSDB') ON CLASS db_authorizations;


/* ADM5000 테이블 생성 SQL */
CREATE TABLE ADM5000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          LOGIN_USR_ID VARCHAR(20) COLLATE utf8_bin NOT NULL ,
          LOGIN_TIME DATETIME NOT NULL ,
          LOGOUT_TIME DATETIME NULL ,
          LOGIN_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          LOGIN_STATUS VARCHAR(20) COLLATE utf8_bin NULL
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM5000','OSLITSDB') ON CLASS db_authorizations;

 
/* ADM5100 테이블 생성 SQL */
CREATE TABLE ADM5100 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NULL ,
          LOG_TIME DATETIME NULL ,
          LOG_URL VARCHAR(500) COLLATE utf8_bin NULL ,
          LOG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          LOG_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MENU_ID VARCHAR(12) COLLATE utf8_bin NULL ,
          MENU_NM VARCHAR(200) COLLATE utf8_bin NULL ,
          MENU_URL VARCHAR(500) COLLATE utf8_bin NULL ,
          MENU_CD VARCHAR(2) COLLATE utf8_bin NULL
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM5100','OSLITSDB') ON CLASS db_authorizations;


/* ADM5200 테이블 생성 SQL */
CREATE TABLE ADM5200 (
          LOG_TIME DATETIME NULL ,
          LOG_STATE VARCHAR(1) COLLATE utf8_bin NULL ,
          USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NULL ,
          USR_PW VARCHAR(200) COLLATE utf8_bin NULL ,
          USR_NM VARCHAR(200) COLLATE utf8_bin NULL ,
          EMAIL VARCHAR(50) COLLATE utf8_bin NULL ,
          TELNO VARCHAR(20) COLLATE utf8_bin NULL ,
          DEPT_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          ETC VARCHAR(4000) COLLATE utf8_bin NULL ,
          WK_ST_TM CHAR(4) COLLATE utf8_bin NULL ,
          WK_ED_TM CHAR(4) COLLATE utf8_bin NULL ,
          BK_ST_TM CHAR(4) COLLATE utf8_bin NULL ,
          BK_ED_TM CHAR(4) COLLATE utf8_bin NULL ,
          PW_FAIL_CNT INT NULL ,
          BLOCK VARCHAR(2) COLLATE utf8_bin NULL ,
          USR_IMG_ID CHAR(20) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          USR_POSITION_CD  VARCHAR(2) COLLATE utf8_bin NULL ,
          USR_DUTY_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REQ_MAIN_COLOR VARCHAR(10) COLLATE utf8_bin NULL ,
          REQ_FONT_COLOR VARCHAR(10) COLLATE utf8_bin NULL ,
          REC_LOGIN_DTM DATETIME NULL ,
          PW_MODIFY_DTM DATETIME NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM5200','OSLITSDB') ON CLASS db_authorizations;

 
/* ADM6000 테이블 생성 SQL */
CREATE TABLE ADM6000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          HOLI_DATE VARCHAR(8) COLLATE utf8_bin NOT NULL ,
          DAY_WEEK CHAR(1) COLLATE utf8_bin NULL ,
          HOLI_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          HOLI_DESC VARCHAR(100) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM6000 PRIMARY KEY ( LIC_GRP_ID, HOLI_DATE )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM6000','OSLITSDB') ON CLASS db_authorizations;


/* ADM7000 테이블 생성 SQL */
CREATE TABLE ADM7000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          DEPT_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          UPPER_DEPT_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          DEPT_NAME VARCHAR(200) COLLATE utf8_bin NOT NULL ,
          DEPT_ADMIN_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          ORD INT NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          DEPT_ETC VARCHAR(4000) COLLATE utf8_bin NULL ,
          LVL INT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_ADM7000 PRIMARY KEY ( LIC_GRP_ID, DEPT_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('ADM7000','OSLITSDB') ON CLASS db_authorizations;

 
/* API1000 테이블 생성 SQL */
CREATE TABLE API1000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          API_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          API_NM VARCHAR(500) COLLATE utf8_bin NULL ,
          API_URL VARCHAR(500) COLLATE utf8_bin NULL ,
          API_TXT VARCHAR(1000) COLLATE utf8_bin NULL ,
          ATCH_FILE_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_API1000 PRIMARY KEY ( LIC_GRP_ID, API_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('API1000','OSLITSDB') ON CLASS db_authorizations;

 
/* API1100 테이블 생성 SQL */
CREATE TABLE API1100 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          PRJ_ID  VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          API_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          API_TOK VARCHAR(50) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_API1100 PRIMARY KEY ( LIC_GRP_ID, PRJ_ID , API_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('API1100','OSLITSDB') ON CLASS db_authorizations;

 
/* BAD1000 테이블 생성 SQL */
CREATE TABLE BAD1000 (
          BAD_ID VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          BAD_NUM VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          BAD_TITLE VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          BAD_CONTENT VARCHAR(2000) COLLATE utf8_bin NULL ,
          BAD_CNT VARCHAR(5000) COLLATE utf8_bin NULL ,
          USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          USR_NM VARCHAR(200) COLLATE utf8_bin NULL ,
          NOTICE_YN VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_BAD1000 PRIMARY KEY ( BAD_ID, LIC_GRP_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('BAD1000','OSLITSDB') ON CLASS db_authorizations;


/* COMTNCOPSEQ 테이블 생성 SQL */
CREATE TABLE COMTNCOPSEQ (
          TABLE_NAME VARCHAR(20) COLLATE utf8_bin NOT NULL ,
          NEXT_ID INT(30) NULL ,
CONSTRAINT PK_COMTNCOPSEQ PRIMARY KEY ( TABLE_NAME )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('COMTNCOPSEQ','OSLITSDB') ON CLASS db_authorizations;


/* COMTNFILE 테이블 생성 SQL */
CREATE TABLE COMTNFILE (
          ATCH_FILE_ID CHAR(20) COLLATE utf8_bin NOT NULL ,
          CREAT_DT DATETIME NULL ,
          USE_AT CHAR(1) COLLATE utf8_bin NULL ,
CONSTRAINT PK_COMTNFILE PRIMARY KEY ( ATCH_FILE_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('COMTNFILE','OSLITSDB') ON CLASS db_authorizations;

 
/* COMTNFILEDETAIL 테이블 생성 SQL */
CREATE TABLE COMTNFILEDETAIL (
          ATCH_FILE_ID CHAR(20) COLLATE utf8_bin NOT NULL ,
          FILE_SN INT(10) NOT NULL ,
          FILE_STRE_COURS VARCHAR(2000) COLLATE utf8_bin NULL ,
          STRE_FILE_NM VARCHAR(255) COLLATE utf8_bin NULL ,
          ORIGNL_FILE_NM VARCHAR(255) COLLATE utf8_bin NULL ,
          FILE_EXTSN VARCHAR(20) COLLATE utf8_bin NULL ,
          FILE_CN CLOB NULL ,
          FILE_SIZE INT(12) NULL ,
          REG_DTM DATETIME NULL ,
CONSTRAINT PK_COMTNFILEDETAIL PRIMARY KEY ( ATCH_FILE_ID, FILE_SN )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('COMTNFILEDETAIL','OSLITSDB') ON CLASS db_authorizations;


/* DPL1000 테이블 생성 SQL */
CREATE TABLE DPL1000 (
          PRJ_ID  VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          DPL_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          DPL_NM VARCHAR(200) COLLATE utf8_bin NOT NULL ,
          DPL_VER VARCHAR(100) COLLATE utf8_bin NULL ,
          DPL_DT  DATETIME NULL ,
          DPL_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          DPL_DESC VARCHAR(1000) COLLATE utf8_bin NULL ,
          DPL_STS_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          DPL_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          DPL_AUTO_AFTER_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          DPL_AUTO_DTM DATETIME NULL ,
          DPL_RESTORE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          DPL_SIGN_TXT VARCHAR(2000) COLLATE utf8_bin NULL ,
          DPL_DEL_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_DPL1000 PRIMARY KEY ( PRJ_ID , DPL_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('DPL1000','OSLITSDB') ON CLASS db_authorizations;

 
/* DPL1100 테이블 생성 SQL */
CREATE TABLE DPL1100 (
          PRJ_ID  VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          FLOW_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          DPL_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_DPL1100 PRIMARY KEY ( PRJ_ID , REQ_ID, PROCESS_ID, FLOW_ID, DPL_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('DPL1100','OSLITSDB') ON CLASS db_authorizations;

 
/* DPL1200 테이블 생성 SQL */
CREATE TABLE DPL1200 (
          PRJ_ID  VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          DPL_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          SIGN_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          SIGN_USR_ID VARCHAR(20) COLLATE utf8_bin NOT NULL ,
          SIGN_TXT VARCHAR(2000) COLLATE utf8_bin NULL ,
          SIGN_STS_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          SIGN_REJECT_TXT VARCHAR(2000) COLLATE utf8_bin NULL ,
          SIGN_DTM DATETIME NULL ,
          SIGN_REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_DPL1200 PRIMARY KEY ( PRJ_ID , DPL_ID, SIGN_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('DPL1200','OSLITSDB') ON CLASS db_authorizations;


/* DPL1300 테이블 생성 SQL */
CREATE TABLE DPL1300 (
          PRJ_ID  VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          DPL_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JEN_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JOB_ID VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          JOB_START_ORD INT NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_DPL1300 PRIMARY KEY ( PRJ_ID , DPL_ID, JEN_ID, JOB_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('DPL1300','OSLITSDB') ON CLASS db_authorizations;



/* DPL1400 테이블 생성 SQL */
CREATE TABLE DPL1400 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          DPL_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JEN_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JOB_ID VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          BLD_SEQ INT NOT NULL ,
          BLD_NUM INT NULL ,
          BLD_MAIN_NUM INT NULL ,
          BLD_RESULT VARCHAR(20) COLLATE utf8_bin NULL ,
          BLD_RESULT_MSG VARCHAR(1000) COLLATE utf8_bin NULL ,
          BLD_DURATION_TM VARCHAR(50) COLLATE utf8_bin NULL ,
          BLD_START_DTM DATETIME NULL ,
          BLD_CONSOLE_LOG CLOB NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_DPL1400 PRIMARY KEY ( PRJ_ID, DPL_ID, JEN_ID, JOB_ID, BLD_SEQ )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('DPL1400','OSLITSDB') ON CLASS db_authorizations;

 
/* DPL1500 테이블 생성 SQL */
CREATE TABLE DPL1500 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          DPL_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          CHG_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          CHG_NUM INT NOT NULL ,
          CHG_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          CHG_NM VARCHAR(500) COLLATE utf8_bin NULL ,
          CHG_OPT_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          CHG_COMMON_CD VARCHAR(50) COLLATE utf8_bin NULL ,
          PRE_VAL VARCHAR(4000) COLLATE utf8_bin NULL ,
          CHG_VAL VARCHAR(4000) COLLATE utf8_bin NULL ,
          CHG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          CHG_DTM DATETIME NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_DPL1500 PRIMARY KEY ( PRJ_ID, DPL_ID, CHG_ID, CHG_NUM )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('DPL1500','OSLITSDB') ON CLASS db_authorizations;

 
/* FLW1000 테이블 생성 SQL */
CREATE TABLE FLW1000 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_NM VARCHAR(100) COLLATE utf8_bin NOT NULL ,
          PROCESS_DESC VARCHAR(4000) COLLATE utf8_bin NULL ,
          PROCESS_CONFIRM_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          PROCESS_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          PROCESS_MIDDLE_DONE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          PROCESS_JSON_DATA CLOB NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          PROCESS_ORD INT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_FLW1000 PRIMARY KEY ( PRJ_ID, PROCESS_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('FLW1000','OSLITSDB') ON CLASS db_authorizations;

 
/* FLW1100 테이블 생성 SQL */
CREATE TABLE FLW1100 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          FLOW_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          FLOW_NEXT_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          FLOW_NM VARCHAR(100) COLLATE utf8_bin NOT NULL ,
          FLOW_ESSENTIAL_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          FLOW_SIGN_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          FLOW_SIGN_STOP_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          FLOW_END_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          FLOW_WORK_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          FLOW_REVISION_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          FLOW_DPL_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          FLOW_AUTH_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          FLOW_TITLE_BG_COLOR VARCHAR(7) COLLATE utf8_bin NULL ,
          FLOW_TITLE_COLOR VARCHAR(7) COLLATE utf8_bin NULL ,
          FLOW_CONTENT_BG_COLOR VARCHAR(7) COLLATE utf8_bin NULL ,
          FLOW_CONTENT_COLOR VARCHAR(7) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_FLW1100 PRIMARY KEY ( PRJ_ID, PROCESS_ID, FLOW_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('FLW1100','OSLITSDB') ON CLASS db_authorizations;


/* FLW1200 테이블 생성 SQL */
CREATE TABLE FLW1200 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          FLOW_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          ITEM_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          ITEM_NM VARCHAR(100) COLLATE utf8_bin NULL ,
          ITEM_CODE VARCHAR(2) COLLATE utf8_bin NULL ,
          ITEM_COMMON_CODE VARCHAR(20) COLLATE utf8_bin NULL ,
          ITEM_ROW_NUM VARCHAR(2) COLLATE utf8_bin NULL ,
          ITEM_TYPE VARCHAR(10) COLLATE utf8_bin NULL ,
          ITEM_LENGTH INT NULL ,
          ITEM_ESSENTIAL_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          ITEM_MODIFY_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          ITEM_ORD INT NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_FLW1200 PRIMARY KEY ( PRJ_ID, PROCESS_ID, FLOW_ID, ITEM_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('FLW1200','OSLITSDB') ON CLASS db_authorizations;

 
/* FLW1300 테이블 생성 SQL */
CREATE TABLE FLW1300 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          FLOW_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          ITEM_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          ITEM_VALUE VARCHAR(4000) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_FLW1300 PRIMARY KEY ( PRJ_ID, REQ_ID, PROCESS_ID, FLOW_ID, ITEM_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('FLW1300','OSLITSDB') ON CLASS db_authorizations;


/* FLW1400 테이블 생성 SQL */
CREATE TABLE FLW1400 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          FLOW_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          SVN_REP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REVISION_NUM VARCHAR(40) COLLATE utf8_bin NOT NULL ,
          REVISION_COMMENT VARCHAR(4000) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_FLW1400 PRIMARY KEY ( PRJ_ID, REQ_ID, PROCESS_ID, FLOW_ID, SVN_REP_ID, REVISION_NUM )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('FLW1400','OSLITSDB') ON CLASS db_authorizations;

 
/* FLW1500 테이블 생성 SQL */
CREATE TABLE FLW1500 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          FLOW_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          AUTH_GRP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          AUTH_GRP_TARGET_CD VARCHAR(2) COLLATE utf8_bin NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_FLW1500 PRIMARY KEY ( PRJ_ID, PROCESS_ID, FLOW_ID, AUTH_GRP_ID, AUTH_GRP_TARGET_CD )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('FLW1500','OSLITSDB') ON CLASS db_authorizations;


/* JEN1000 테이블 생성 SQL */
CREATE TABLE JEN1000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          JEN_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JEN_NM VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          JEN_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          JEN_USR_TOK VARCHAR(1000) COLLATE utf8_bin NULL ,
          JEN_URL VARCHAR(500) COLLATE utf8_bin NULL ,
          JEN_DESC VARCHAR(2000) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          DEL_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_JEN1000 PRIMARY KEY ( LIC_GRP_ID, JEN_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('JEN1000','OSLITSDB') ON CLASS db_authorizations;

 
/* JEN1100 테이블 생성 SQL */
CREATE TABLE JEN1100 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          JEN_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JOB_ID VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          JOB_RESTORE_ID VARCHAR(500) COLLATE utf8_bin NULL ,
          JOB_TOK VARCHAR(200) COLLATE utf8_bin NULL ,
          JOB_DESC VARCHAR(2000) COLLATE utf8_bin NULL ,
          JOB_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_JEN1100 PRIMARY KEY ( LIC_GRP_ID, JEN_ID, JOB_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('JEN1100','OSLITSDB') ON CLASS db_authorizations;

 
/* JEN1200 테이블 생성 SQL */
CREATE TABLE JEN1200 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JEN_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JOB_ID VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_JEN1200 PRIMARY KEY ( LIC_GRP_ID, PRJ_ID, JEN_ID, JOB_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('JEN1200','OSLITSDB') ON CLASS db_authorizations;


/* JEN1300 테이블 생성 SQL */
CREATE TABLE JEN1300 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JEN_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          JOB_ID VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          AUTH_GRP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_JEN1300 PRIMARY KEY ( LIC_GRP_ID, PRJ_ID, JEN_ID, JOB_ID, AUTH_GRP_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('JEN1300','OSLITSDB') ON CLASS db_authorizations;


/* MIL1000 테이블 생성 SQL */
CREATE TABLE MIL1000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          MILESTONE_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          MEILSTONE_NAME VARCHAR(200) COLLATE utf8_bin NOT NULL ,
          START_DT DATETIME NULL ,
          END_DT DATETIME NULL ,
          CREATE_DT DATETIME NULL ,
          USE_CD DATETIME NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_MIL1000 PRIMARY KEY ( LIC_GRP_ID, PRJ_ID, MILESTONE_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('MIL1000','OSLITSDB') ON CLASS db_authorizations;

; 
/* PRJ1000 테이블 생성 SQL */
CREATE TABLE PRJ1000 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          PRJ_GRP_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          PRJ_NM VARCHAR(200) COLLATE utf8_bin NOT NULL ,
          START_DT CHAR(8) COLLATE utf8_bin NULL ,
          END_DT CHAR(8) COLLATE utf8_bin NULL ,
          ORD INT NULL ,
          PRJ_DESC VARCHAR(4000) COLLATE utf8_bin NULL ,
          USE_CD CHAR(2) COLLATE utf8_bin NULL ,
          PRJ_TYPE CHAR(2) COLLATE utf8_bin NULL ,
          PRJ_ACRM VARCHAR(10) COLLATE utf8_bin NULL ,
          PRJ_GRP_CD CHAR(2) COLLATE utf8_bin NULL ,
          PRJ_TASK_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_PRJ1000 PRIMARY KEY ( PRJ_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('PRJ1000','OSLITSDB') ON CLASS db_authorizations;


/* PRJ3000 테이블 생성 SQL */
CREATE TABLE PRJ3000 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          DOC_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          UPPER_DOC_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          DOC_NM VARCHAR(200) COLLATE utf8_bin NOT NULL ,
          DOC_DESC VARCHAR(500) COLLATE utf8_bin NULL ,
          DOC_FORM_FILE_ID CHAR(20) COLLATE utf8_bin NULL ,
          DOC_FORM_FILE_SN INT(10) NULL ,
          DOC_ATCH_FILE_ID CHAR(20) COLLATE utf8_bin NULL ,
          DOC_FILE_SN INT(10) NULL ,
          DOC_CONF_DESC VARCHAR(500) COLLATE utf8_bin NULL ,
          LVL INT NULL ,
          ORD INT NULL ,
          DOC_ED_DTM DATETIME NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_PRJ3000 PRIMARY KEY ( PRJ_ID, DOC_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('PRJ3000','OSLITSDB') ON CLASS db_authorizations;


/* REQ4000 테이블 생성 SQL */
CREATE TABLE REQ4000 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_CLS_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          UPPER_REQ_CLS_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          REQ_CLS_NM VARCHAR(200) COLLATE utf8_bin NOT NULL ,
          LVL INT NULL ,
          ORD INT NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_REQ4000 PRIMARY KEY ( PRJ_ID, REQ_CLS_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('REQ4000','OSLITSDB') ON CLASS db_authorizations;


/* REQ4100 테이블 생성 SQL */
CREATE TABLE REQ4100 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_CLS_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          REQ_NO VARCHAR(100) COLLATE utf8_bin NULL ,
          REQ_ORD VARCHAR(100) COLLATE utf8_bin NULL ,
          REQ_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REQ_USR_NM VARCHAR(200) COLLATE utf8_bin NULL ,
          REQ_DTM DATETIME NULL ,
          REQ_USR_DEPT_NM VARCHAR(500) COLLATE utf8_bin NULL ,
          REQ_USR_POSITION_NM VARCHAR(500) COLLATE utf8_bin NULL ,
          REQ_USR_DUTY_NM VARCHAR(500) COLLATE utf8_bin NULL ,
          REQ_USR_EMAIL VARCHAR(100) COLLATE utf8_bin NULL ,
          REQ_USR_NUM VARCHAR(11) COLLATE utf8_bin NULL ,
          REQ_NM VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          REQ_DESC VARCHAR(4000) COLLATE utf8_bin NULL ,
          REQ_CHARGER_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REQ_COMPLETE_RATIO INT DEFAULT '0' NULL ,
          REQ_FP INT DEFAULT '0' NULL ,
          REQ_EX_FP INT DEFAULT '0' NULL ,
          REQ_ST_DTM DATETIME NULL ,
          REQ_ED_DTM DATETIME NULL ,
          REQ_ST_DU_DTM DATETIME NULL ,
          REQ_ED_DU_DTM DATETIME NULL ,
          REQ_PRO_TYPE VARCHAR(2) DEFAULT '01' COLLATE utf8_bin NULL ,
          REQ_NEW_TYPE VARCHAR(2) COLLATE utf8_bin NULL ,
          REQ_ACCEPT_TXT VARCHAR(4000) COLLATE utf8_bin NULL ,
          SCL_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REQ_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          PIA_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          LAB_INP INT DEFAULT '0' NULL ,
          LAB_INP_RESULT_TXT VARCHAR(4000) COLLATE utf8_bin NULL ,
          REQ_GRUND_TXT VARCHAR(4000) COLLATE utf8_bin NULL ,
          ATCH_FILE_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          CB_ATCH_FILE_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MILESTONE_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          FLOW_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          ORG_REQ_ID VARCHAR(4000) COLLATE utf8_bin NULL ,
          REQ_KEY VARCHAR(500) COLLATE utf8_bin NULL ,
          REQ_MIDDLE_DONE_TXT VARCHAR(4000) COLLATE utf8_bin NULL ,
          REQ_TASK_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REQ_WORK_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REQ_MNG_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REQ_MNG_DETAIL_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REQ_MNG_TASK_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_REQ4100 PRIMARY KEY ( PRJ_ID, REQ_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('REQ4100','OSLITSDB') ON CLASS db_authorizations;


/* REQ4300 테이블 생성 SQL */
CREATE TABLE REQ4300 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_CMNT_SEQ INT NOT NULL ,
          REQ_CMNT VARCHAR(4000) COLLATE utf8_bin NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_REQ4300 PRIMARY KEY ( PRJ_ID, REQ_ID, REQ_CMNT_SEQ )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('REQ4300','OSLITSDB') ON CLASS db_authorizations;


/* REQ4400 테이블 생성 SQL */
CREATE TABLE REQ4400 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          FLOW_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          WORK_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          WORK_STATUS_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WORK_ADM_CONTENT VARCHAR(4000) COLLATE utf8_bin NULL ,
          WORK_CHARGER_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          WORK_ADM_ST_DTM DATETIME NULL ,
          WORK_ADM_ED_DTM DATETIME NULL ,
          WORK_CONTENT VARCHAR(4000) COLLATE utf8_bin NULL ,
          WORK_ST_DTM DATETIME NULL ,
          WORK_ED_DTM DATETIME NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_REQ4400 PRIMARY KEY ( PRJ_ID, REQ_ID, PROCESS_ID, FLOW_ID, WORK_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('REQ4400','OSLITSDB') ON CLASS db_authorizations;


/* REQ4600 테이블 생성 SQL */
CREATE TABLE REQ4600 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_CB_SEQ INT NOT NULL ,
          CB_FILE_SN INT(10) NULL ,
          CB_GB_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          CB_CONTENT_TEXT CLOB NULL ,
          CB_THUM_VIEW_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_REQ4600 PRIMARY KEY ( PRJ_ID, REQ_ID, REQ_CB_SEQ )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('REQ4600','OSLITSDB') ON CLASS db_authorizations;


/* REQ4700 테이블 생성 SQL */
CREATE TABLE REQ4700 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_CHG_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_CHG_TYPE VARCHAR(2) COLLATE utf8_bin NULL ,
          CHG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          CHG_DTM DATETIME NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          PRE_FLOW_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          CHG_FLOW_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          PRE_CHARGER_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          CHG_CHARGER_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_REQ4700 PRIMARY KEY ( PRJ_ID, REQ_ID, REQ_CHG_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('REQ4700','OSLITSDB') ON CLASS db_authorizations;


/* REQ4800 테이블 생성 SQL */
CREATE TABLE REQ4800 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          CHG_DETAIL_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          CHG_DETAIL_NUM VARCHAR(18) COLLATE utf8_bin NOT NULL ,
          CHG_DETAIL_TYPE VARCHAR(2) COLLATE utf8_bin NULL ,
          CHG_DETAIL_NM VARCHAR(200) COLLATE utf8_bin NULL ,
          CHG_DETAIL_OPT_TYPE VARCHAR(20) COLLATE utf8_bin NULL ,
          CHG_DETAIL_COMMON_CD VARCHAR(8) COLLATE utf8_bin NULL ,
          PRE_DETAIL_VAL VARCHAR(4000) COLLATE utf8_bin NULL ,
          CHG_DETAIL_VAL VARCHAR(4000) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_REQ4800 PRIMARY KEY ( PRJ_ID, REQ_ID, CHG_DETAIL_ID, CHG_DETAIL_NUM )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('REQ4800','OSLITSDB') ON CLASS db_authorizations;

 
/* REQ4900 테이블 생성 SQL */
CREATE TABLE REQ4900 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REQ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          SIGN_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PROCESS_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          SIGN_PREV_FLOW_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          SIGN_FLOW_ID VARCHAR(16) COLLATE utf8_bin NULL ,
          SIGN_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          SIGN_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          SIGN_REJECT_CMNT VARCHAR(4000) COLLATE utf8_bin NULL ,
          SIGN_DTM DATETIME NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_REQ4900 PRIMARY KEY ( PRJ_ID, REQ_ID, SIGN_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('REQ4900','OSLITSDB') ON CLASS db_authorizations;

 
/* SVN1000 테이블 생성 SQL */
CREATE TABLE SVN1000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          SVN_REP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          SVN_REP_NM VARCHAR(500) COLLATE utf8_bin NOT NULL ,
          SVN_REP_URL VARCHAR(500) COLLATE utf8_bin NULL ,
          SVN_TXT VARCHAR(1000) COLLATE utf8_bin NULL ,
          SVN_USR_ID VARCHAR(30) COLLATE utf8_bin NULL ,
          SVN_USR_PW VARCHAR(1000) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_SVN1000 PRIMARY KEY ( LIC_GRP_ID, SVN_REP_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('SVN1000','OSLITSDB') ON CLASS db_authorizations;

 
/* SVN1100 테이블 생성 SQL */
CREATE TABLE SVN1100 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          SVN_REP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_SVN1100 PRIMARY KEY ( LIC_GRP_ID, SVN_REP_ID, PRJ_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('SVN1100','OSLITSDB') ON CLASS db_authorizations;

 
/* SVN1200 테이블 생성 SQL */
CREATE TABLE SVN1200 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          SVN_REP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          AUTH_GRP_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_SVN1200 PRIMARY KEY ( PRJ_ID, SVN_REP_ID, AUTH_GRP_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('SVN1200','OSLITSDB') ON CLASS db_authorizations;


/* WHK1000 테이블 생성 SQL */
CREATE TABLE WHK1000 (
          PRJ_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          WEBHOOK_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          WEBHOOK_NM VARCHAR(100) COLLATE utf8_bin NULL ,
          PLATFORM_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WEBHOOK_URL VARCHAR(500) COLLATE utf8_bin NULL ,
          WHK_REQ_UPDATE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_REQ_DELETE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_FLOW_CHG_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_NEW_INSERT_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_NEW_ACCEPT_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_NEW_REJECT_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_SIGN_REQUEST_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_SIGN_ACCEPT_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_SIGN_REJECT_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_USER_CHG_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_REQ_DONE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_WHK1000 PRIMARY KEY ( PRJ_ID, WEBHOOK_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('WHK1000','OSLITSDB') ON CLASS db_authorizations;


/* WHK2000 테이블 생성 SQL */
CREATE TABLE WHK2000 (
          LIC_GRP_ID VARCHAR(23) COLLATE utf8_bin NOT NULL ,
          USR_ID VARCHAR(20) COLLATE utf8_bin NOT NULL ,
          WEBHOOK_ID VARCHAR(16) COLLATE utf8_bin NOT NULL ,
          WEBHOOK_NM VARCHAR(100) COLLATE utf8_bin NULL ,
          PLATFORM_TYPE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WEBHOOK_URL VARCHAR(500) COLLATE utf8_bin NULL ,
          WHK_REQ_DELETE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_FLOW_CHG_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_NEW_ACCEPT_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_NEW_REJECT_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_SIGN_REQUEST_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_SIGN_ACCEPT_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_SIGN_REJECT_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_USER_CHG_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_REQ_DONE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          WHK_MEMO_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          USE_CD VARCHAR(2) COLLATE utf8_bin NULL ,
          REG_DTM DATETIME NULL ,
          REG_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          REG_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
          MODIFY_DTM DATETIME NULL ,
          MODIFY_USR_ID VARCHAR(20) COLLATE utf8_bin NULL ,
          MODIFY_USR_IP VARCHAR(39) COLLATE utf8_bin NULL ,
CONSTRAINT PK_WHK2000 PRIMARY KEY ( LIC_GRP_ID, USR_ID, WEBHOOK_ID )
) COLLATE utf8_bin  REUSE_OID ;
CALL CHANGE_OWNER ('WHK2000','OSLITSDB') ON CLASS db_authorizations;

